apiVersion: v1
kind: Secret
metadata:
  name: {{ template "taiga.fullname" . }}
  labels:
{{ include "taiga.labels" . | indent 4 }}
data:
  dbPassword: {{ .Values.taiga.dbPassword | required "taiga.dbPassword must be set" | b64enc }}
  secretKey: {{ .Values.taiga.secretKey | default ( randAlphaNum 10 ) |  b64enc }}
  {{ if .Values.taiga.emailEnabled }}emailSmtpPassword: {{ required "taiga.emailSmtpPassword must be set" .Values.taiga.emailSmtpPassword | b64enc }}{{ end }}
