apiVersion: v1
kind: Service
metadata:
  name: {{ template "taiga.fullname" . }}-headless
  labels:
{{ include "taiga.labels" . | indent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
  selector:
{{ include "taiga.labels" . | indent 4 }}
